services:
  debian-min-sys:    
    build: .
    image: debian-base1-sys:latest
    container_name: debian-base1
    ports:
      - "3389:3389"
      - "49002:49002"
    environment:
      - CIS4900_CLASSROOMS_FILE=/opt/cis4900/classrooms.json
      - PYTHONUNBUFFERED=1
    volumes:
      # mapping this folder to the work folder directory for testuser
      - .:/home/testuser/work 