[global]
    origin = "top-right"
    offset = "20x20"
    width = 260
    font = Monospace 10
    frame_width = 1
    frame_color = "#444444"
    separator_color = "#444444"
    gap_size = 4
    corner_radius = 4

[urgency_low]
    background = "#262626"
    foreground = "#ffffff"
    timeout = 4

[urgency_normal]
    background = "#262626"
    foreground = "#ffffff"
    timeout = 4

[urgency_critical]
    background = "#900000"
    foreground = "#ffffff"
    timeout = 0
