backend = "xrender";
vsync = false;
fading = false;
shadow = false;

# Force full screen redraw on every frame to fix i3 tiles resize as it misses changed regions
use-damage = false;

# Prevent compositing toggle flicker on window state changes
unredir-if-possible = false;

# respect ARGB alpha channels set by client windows like i3
detect-client-opacity = true;
 
# for transparency
active-opacity = 1.0;
inactive-opacity = 1.0;
frame-opacity = 1.0;
 
opacity-rule = [
    "0:_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'",
    "92:name = 'polybar-hover'",
    "40:name = 'polybar'"
];
 
# ensure picom composites dock-type windows like the i3 bar so ARGB transparency works
wintypes:
{
    dock = { shadow = false; };
};