backend = "xrender";
vsync = false;
fading = false;
shadow = false;

# Force full screen redraw on every frame to eliminate i3 tiles resize artifacts  
# this is because damage tracking misses changed regions
use-damage = false;

# Prevent compositing toggle flicker on window state changes
unredir-if-possible = false;